//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka6.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryZakaz
    {
        public int Id { get; set; }
        public int Byers_Id { get; set; }
        public int TovarId { get; set; }
        public int Status_Id { get; set; }
        public Nullable<System.DateTime> TimeDelivery { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> PayMethodID { get; set; }
        public Nullable<int> Ocenka { get; set; }
    
        public virtual Byers Byers { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PayMethod PayMethod { get; set; }
        public virtual StatusZakaz StatusZakaz { get; set; }
        public virtual Tovars Tovars { get; set; }
    }
}
