//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka6.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptekaWPFEntities1 : DbContext
    {
        public AptekaWPFEntities1()
            : base("name=AptekaWPFEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Byers> Byers { get; set; }
        public virtual DbSet<CategoryTovar> CategoryTovar { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Favourites> Favourites { get; set; }
        public virtual DbSet<HistoryZakaz> HistoryZakaz { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<PayMethod> PayMethod { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<StatusZakaz> StatusZakaz { get; set; }
        public virtual DbSet<Tovars> Tovars { get; set; }
    }
}
