//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka6.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Id { get; set; }
        public Nullable<int> ByerID { get; set; }
        public Nullable<int> TovarID { get; set; }
        public string Review { get; set; }
    
        public virtual Byers Byers { get; set; }
        public virtual Tovars Tovars { get; set; }
    }
}
