//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka6.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovars()
        {
            this.Favourites = new HashSet<Favourites>();
            this.HistoryZakaz = new HashSet<HistoryZakaz>();
            this.Reviews = new HashSet<Reviews>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> SrokGodnostiDate { get; set; }
        public string Info { get; set; }
        public string Instuction { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SrokGodnosti { get; set; }
        public Nullable<bool> Resept { get; set; }
    
        public virtual CategoryTovar CategoryTovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourites> Favourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryZakaz> HistoryZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
